### ISSUE TITLE
rust-analyzer type hints are colored invasively

### ISSUE THREAD

**Issue by grottohub** [trag1c/gleam-theme#6]
when using rust-analyzer with the most recent theme update, the type hints stand out a lot due to whatever palette they're picking from (i will say i have no idea how plugins or themes work so not sure how feasible changing this is).

default vscode theme with rust-analyzer:

![default vscode theme with rust-analyzer](https://github.com/trag1c/gleam-theme/assets/18193667/3c7c686d-27f3-4ade-a8ca-5e93383dcff4)

gleam theme without rust-analyzer:

![gleam theme without rust-analyzer](https://github.com/trag1c/gleam-theme/assets/18193667/2c8dce22-2d16-4ea4-be4c-ac0df97d1d9a)

gleam theme with rust-analyzer:

![gleam theme with rust-analyzer](https://github.com/trag1c/gleam-theme/assets/18193667/ae6793fb-6027-4d9a-8dc0-d9c28182444a)

**Comment by trag1c** [comment]
how's this? :)

<img width="672" alt="74455" src="https://github.com/trag1c/gleam-theme/assets/77130613/0f26d0aa-9d0d-418b-9cc6-a935c151a2f4">

**Comment by grottohub** [comment]
very nice!
